const characters = [
    { id: 1, name: "Goku", ki: "60.000.000", maxKi: "90 Septillion", race: "Saiyan", gender: "Male", genderType: "Hombre", description: "El protagonista de la serie, conocido por su gran poder y personalidad amigable. Originalmente enviado a la Tierra como un infante volador con la misión de conquistarla. Sin embargo, el caer por un barranco le proporcionó un brutal golpe que si bien casi lo mata, este alteró su memoria y anuló todos los instintos violentos de su especie, lo que lo hizo crecer con un corazón puro y bondadoso, pero conservando todos los poderes de su raza. No obstante, en la nueva continuidad de Dragon Ball se establece que él fue enviado por sus padres a la Tierra con el objetivo de sobrevivir a toda costa a la destrucción de su planeta por parte de Freeza. Más tarde, Kakarot, ahora conocido como Son Goku, se convertiría en el príncipe consorte del monte Fry-pan y líder de los Guerreros Z, así como el mayor defensor de la Tierra y del Universo 7, logrando mantenerlos a salvo de la destrucción en innumerables ocasiones, a pesar de no considerarse a sí mismo como un héroe o salvador.", image: "https://dragonball-api.com/characters/goku_normal.webp", affiliation: "Z Fighter", deletedAt: null },
    { id: 2, name: "Vegeta", ki: "55.000.000", maxKi: "88 Septillion", race: "Saiyan", gender: "Male", genderType: "Hombre", description: "El príncipe de los Saiyans y rival de Goku. Vegeta es orgulloso y ambicioso, siempre buscando superar a Goku en poder. Aunque comenzó como un antagonista, eventualmente se une a los Guerreros Z y lucha por la Tierra.", image: "https://dragonball-api.com/characters/vegeta_normal.webp", affiliation: "Z Fighter", deletedAt: null },
    { id: 3, name: "Gohan", ki: "45.000.000", maxKi: "75 Septillion", race: "Half-Saiyan", gender: "Male", genderType: "Hombre", description: "El hijo mayor de Goku, conocido por su gran potencial de poder. Aunque inicialmente es un guerrero reacio, Gohan se convierte en un formidable luchador y juega un papel crucial en varias batallas importantes.", image: "https://i.pinimg.com/564x/31/2a/0d/312a0d9e67668694f35a7249233d91e0.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 4, name: "Piccolo", ki: "30.000.000", maxKi: "50 Septillion", race: "Namekian", gender: "Male", genderType: "Hombre", description: "Un guerrero Namekiano y antiguo enemigo de Goku que eventualmente se convierte en uno de sus aliados más fuertes. Piccolo es conocido por su inteligencia, disciplina y técnicas de lucha únicas.", image: "https://i.pinimg.com/564x/30/32/4a/30324ada38287857c85c2389d0154319.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 5, name: "Trunks", ki: "35.000.000", maxKi: "60 Septillion", race: "Half-Saiyan", gender: "Male", genderType: "Hombre", description: "El hijo del futuro de Vegeta y Bulma. Trunks es un guerrero valiente y habilidoso que viaja en el tiempo para advertir a los Guerreros Z de amenazas futuras.", image: "https://i.pinimg.com/564x/4a/e2/1a/4ae21a712b66fa56507b5f20d85d49c7.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 6, name: "Bulma", ki: "No Combat", maxKi: "N/A", race: "Human", gender: "Female", genderType: "Mujer", description: "Una genio científica y una de las amigas más cercanas de Goku. Bulma es responsable de muchos avances tecnológicos que ayudan a los Guerreros Z en sus batallas.", image: "https://i.pinimg.com/564x/1b/74/41/1b7441d0826bec6cb366f151069d3e42.jpg", affiliation: "Capsule Corp", deletedAt: null },
    { id: 7, name: "Krillin", ki: "25.000.000", maxKi: "40 Septillion", race: "Human", gender: "Male", genderType: "Hombre", description: "El mejor amigo de Goku y uno de los luchadores humanos más poderosos. Krillin es valiente y siempre dispuesto a luchar por la justicia, a pesar de sus limitaciones en comparación con los Saiyans.", image: "https://i.pinimg.com/564x/a4/bb/c2/a4bbc2900ba336af1e6d7ce1738a69c0.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 8, name: "Tien Shinhan", ki: "23.000.000", maxKi: "35 Septillion", race: "Human", gender: "Male", genderType: "Hombre", description: "Un artista marcial humano con un tercer ojo, conocido por sus técnicas de lucha únicas y su gran dedicación al entrenamiento. Tien es un aliado fiel de los Guerreros Z.", image: "https://i.pinimg.com/564x/1e/73/28/1e7328b1c7aa2793309b242f83c67cbd.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 9, name: "Yamcha", ki: "20.000.000", maxKi: "30 Septillion", race: "Human", gender: "Male", genderType: "Hombre", description: "Un antiguo bandido del desierto que se convierte en uno de los amigos más cercanos de Goku. Aunque a menudo es superado por otros, Yamcha sigue siendo un luchador valiente y un miembro valioso del equipo.", image: "https://i.pinimg.com/564x/ec/0a/dd/ec0addb87e7b8eb996bcb9cd165bb1b2.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 10, name: "Chiaotzu", ki: "15.000.000", maxKi: "25 Septillion", race: "Human", gender: "Male", genderType: "Hombre", description: "Un pequeño luchador con habilidades psíquicas y el mejor amigo de Tien. Chiaotzu es valiente y siempre está dispuesto a sacrificarse por sus amigos.", image: "https://i.pinimg.com/564x/f0/a4/f3/f0a4f327f9fb38503d88c3696a461260.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 11, name: "Frieza", ki: "100.000.000", maxKi: "100 Septillion", race: "Frieza Race", gender: "Male", genderType: "Hombre", description: "Uno de los villanos más icónicos de Dragon Ball, conocido por su crueldad y su inmenso poder. Frieza es el emperador del universo y tiene la capacidad de transformarse para aumentar su poder.", image: "https://i.pinimg.com/564x/97/da/c4/97dac4a6fc230cf66c43daf0bf1d6cc5.jpg", affiliation: "Self", deletedAt: null },
    { id: 12, name: "Cell", ki: "120.000.000", maxKi: "120 Septillion", race: "Bio-Android", gender: "Male", genderType: "Hombre", description: "Un bio-androide creado por el Dr. Gero que posee las habilidades de muchos de los luchadores más poderosos de la Tierra. Cell busca la perfección y está dispuesto a destruir cualquier cosa en su camino.", image: "https://i.pinimg.com/564x/71/4c/63/714c639b8de27d046af9f1013cff07ca.jpg", affiliation: "Self", deletedAt: null },
    { id: 13, name: "Majin Buu", ki: "150.000.000", maxKi: "150 Septillion", race: "Majin", gender: "Male", genderType: "Hombre", description: "Un ser mágico con un poder inmenso y una personalidad impredecible. Majin Buu tiene la capacidad de regenerarse y cambiar de forma, lo que lo hace un adversario extremadamente peligroso.", image: "https://i.pinimg.com/564x/9b/c4/e6/9bc4e66e49b5dcad0a0def1e6a08a422.jpg", affiliation: "Self", deletedAt: null },
    { id: 14, name: "Broly", ki: "160.000.000", maxKi: "160 Septillion", race: "Saiyan", gender: "Male", genderType: "Hombre", description: "Un Saiyan legendario con un poder abrumador que rivaliza con Goku y Vegeta. Broly es conocido por su fuerza bruta y su capacidad de aumentar su poder sin límites aparentes.", image: "https://i.pinimg.com/564x/54/fb/63/54fb63ced89797e00764678c09ad840a.jpg", affiliation: "Self", deletedAt: null },
    { id: 15, name: "Beerus", ki: "180.000.000", maxKi: "180 Septillion", race: "God of Destruction", gender: "Male", genderType: "Hombre", description: "El Dios de la Destrucción del Universo 7, conocido por su poder devastador y su naturaleza impredecible. Beerus mantiene el equilibrio en el universo destruyendo planetas y civilizaciones.", image: "https://i.pinimg.com/564x/b4/33/61/b4336194140437ed60e5854f45b7d6bf.jpg", affiliation: "Self", deletedAt: null },
    { id: 16, name: "Whis", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Angel", gender: "Male", genderType: "Hombre", description: "El ángel asistente de Beerus y uno de los seres más poderosos del universo. Whis es un mentor para Goku y Vegeta, ayudándoles a alcanzar nuevos niveles de poder.", image: "https://i.pinimg.com/564x/7c/d6/21/7cd621904ced9030317f46a6a17d2258.jpg", affiliation: "Self", deletedAt: null },
    { id: 17, name: "Jiren", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Unknown", gender: "Male", genderType: "Hombre", description: "Un miembro de los Pride Troopers del Universo 11, conocido por su fuerza abrumadora. Jiren es uno de los oponentes más fuertes que Goku ha enfrentado.", image: "https://i.pinimg.com/564x/6e/f2/99/6ef299770dc37af5bc8002213f88432f.jpg", affiliation: "Pride Troopers", deletedAt: null },
    { id: 18, name: "Goten", ki: "30.000.000", maxKi: "50 Septillion", race: "Half-Saiyan", gender: "Male", genderType: "Hombre", description: "El hijo menor de Goku, conocido por su gran potencial de poder desde una edad temprana. Goten es alegre y travieso, siempre dispuesto a entrenar y pelear.", image: "https://i.pinimg.com/564x/b8/f1/22/b8f12200cf2009e5e073ef211c650a81.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 19, name: "Android 18", ki: "30.000.000", maxKi: "50 Septillion", race: "Android", gender: "Female", genderType: "Mujer", description: "Una de los androides creados por el Dr. Gero. Android 18 inicialmente era una villana, pero se redime y se convierte en una aliada de los Guerreros Z y la esposa de Krillin.", image: "https://i.pinimg.com/736x/16/5f/d4/165fd4cfdebdb453f58327f7c8383673.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 20, name: "Android 17", ki: "30.000.000", maxKi: "50 Septillion", race: "Android", gender: "Male", genderType: "Hombre", description: "El hermano gemelo de Android 18, conocido por su fuerza y habilidades únicas. Android 17 también se redime y lucha junto a los Guerreros Z.", image: "https://i.pinimg.com/564x/e3/f4/b7/e3f4b7ba99745901a8a818963705295e.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 21, name: "Hercule", ki: "No Combat", maxKi: "N/A", race: "Human", gender: "Male", genderType: "Hombre", description: "Un campeón de artes marciales conocido por su valentía, aunque es mucho menos poderoso que los Guerreros Z. Hercule a menudo toma crédito por las victorias de otros.", image: "https://i.pinimg.com/564x/19/60/35/196035146d1e4fc6b409e3cb3072d480.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 22, name: "Videl", ki: "10.000.000", maxKi: "20 Septillion", race: "Human", gender: "Female", genderType: "Mujer", description: "La hija de Hercule y una talentosa artista marcial. Videl se casa con Gohan y se convierte en una luchadora fuerte y valiente.", image: "https://i.pinimg.com/564x/03/de/f0/03def05eb146e6e495065ea12aac92e4.jpg", affiliation: "Z Fighter", deletedAt: null },
    { id: 23, name: "Kefla", ki: "90.000.000", maxKi: "90 Septillion", race: "Saiyan Fusion", gender: "Female", genderType: "Mujer", description: "La fusión de Caulifla y Kale del Universo 6, conocida por su inmenso poder y su naturaleza feroz. Kefla es una guerrera formidable que desafía a Goku.", image: "https://i.pinimg.com/564x/b1/ee/1a/b1ee1ac85ae15dd24ca9df465aa3c68a.jpg", affiliation: "Self", deletedAt: null },
    { id: 24, name: "Hit", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Unknown", gender: "Male", genderType: "Hombre", description: "Un asesino del Universo 6 conocido por su habilidad de manipular el tiempo. Hit es uno de los guerreros más formidables de su universo.", image: "https://i.pinimg.com/564x/de/58/5d/de585d31f7080d4e8d34ecb2d5792cb1.jpg", affiliation: "Self", deletedAt: null },
    { id: 25, name: "Zamasu", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Kai", gender: "Male", genderType: "Hombre", description: "Un ex Kai Supremo del Universo 10 que se vuelve malvado y busca la inmortalidad. Zamasu tiene una rivalidad feroz con Goku.", image: "https://i.pinimg.com/564x/5f/7c/12/5f7c12c58e9867d5c6064d1c1c4ee725.jpg", affiliation: "Self", deletedAt: null },
    { id: 26, name: "Goku Black", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Saiyan", gender: "Male", genderType: "Hombre", description: "La versión malvada de Goku de una línea temporal alternativa, fusionado con Zamasu. Goku Black es uno de los enemigos más peligrosos de los Guerreros Z.", image: "https://i.pinimg.com/564x/69/9a/75/699a75f40da61ea5d83912236d3af6ac.jpg", affiliation: "Self", deletedAt: null },
    { id: 27, name: "Caulifla", ki: "70.000.000", maxKi: "70 Septillion", race: "Saiyan", gender: "Female", genderType: "Mujer", description: "Una Saiyan del Universo 6 conocida por su naturaleza rebelde y su gran potencial de poder. Caulifla es una luchadora feroz y siempre busca hacerse más fuerte.", image: "https://i.pinimg.com/564x/f0/97/c7/f097c7853c18c34cca474012619ccb07.jpg", affiliation: "Self", deletedAt: null },
    { id: 28, name: "Kale", ki: "70.000.000", maxKi: "70 Septillion", race: "Saiyan", gender: "Female", genderType: "Mujer", description: "Una Saiyan del Universo 6 y amiga cercana de Caulifla. Kale tiene un gran poder latente que rivaliza con el de los Saiyans legendarios.", image: "https://i.pinimg.com/564x/58/21/d5/5821d54f26dec7d3b4f47513f0140cd1.jpg", affiliation: "Self", deletedAt: null },
    { id: 29, name: "Cabba", ki: "60.000.000", maxKi
    : "60 Septillion", race: "Saiyan", gender: "Male", genderType: "Hombre", description: "Un Saiyan del Universo 6 conocido por su humildad y su deseo de proteger a los demás. Cabba se convierte en un estudiante de Vegeta y aprende a transformarse en Super Saiyan.", image: "https://i.pinimg.com/564x/72/ae/62/72ae627245910305888b11b0951eb4e6.jpg", affiliation: "Self", deletedAt: null },
    { id: 30, name: "Toppo", ki: "Unmeasurable", maxKi: "Unmeasurable", race: "Unknown", gender: "Male", genderType: "Hombre", description: "El líder de los Pride Troopers del Universo 11 y un candidato a Dios de la Destrucción. Toppo es un guerrero honorable que lucha por la justicia.", image: "https://i.pinimg.com/564x/20/ca/b0/20cab05ac34fd36cef24262d0c4350fb.jpg", affiliation: "Pride Troopers", deletedAt: null }
];

// Obtener elementos del DOM
const characterTableBody = document.getElementById('character-table-body');
const characterDetails = document.getElementById('character-details');
const genderFilter = document.getElementById('gender-filter');

// Función para mostrar los personajes según el filtro de género
function displayCharacters(filter) {
    characterTableBody.innerHTML = '';
    characters.forEach(character => {
        if ((filter === 'todos') || (filter === 'hombres' && character.genderType === 'Hombre') || (filter === 'mujeres' && character.genderType === 'Mujer')) {
            const row = document.createElement('tr');
            row.innerHTML = `<td>${character.id}</td><td>${character.name}</td>`;
            row.addEventListener('click', () => {
                characterDetails.innerHTML = `
                    <div class="character-card">
                        <img src="${character.image}" alt="${character.name}">
                        <div>
                            <h2>${character.name}</h2>
                            <p><strong>ID:</strong> ${character.id}</p>
                            <p><strong>Ki:</strong> ${character.ki}</p>
                            <p><strong>Max Ki:</strong> ${character.maxKi}</p>
                            <p><strong>Raza:</strong> ${character.race}</p>
                            <p><strong>Género:</strong> ${character.gender}</p>
                            <p><strong>Tipo:</strong> ${character.genderType}</p>
                            <p><strong>Descripción:</strong> ${character.description}</p>
                            <p><strong>Afiliación:</strong> ${character.affiliation}</p>
                        </div>
                    </div>
                `;
            });
            characterTableBody.appendChild(row);
        }
    });
}

// Event listener para el cambio en el filtro de género
genderFilter.addEventListener('change', () => {
    displayCharacters(genderFilter.value);
});

// Mostrar todos los personajes por defecto
displayCharacters('todos');
